# Setup
title:               Yong
tagline:             'Developer Yong'
description:         'Developer'
url:                 https://yong8802.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Yong
  url:
  email:             yong880211@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
